[package]
name = "scraper_types"
version = "0.2.0"
edition = "2024"

[dependencies]
chrono = { workspace = true }
mlua = { version = "0.11", features = ["lua54", "serialize", "send", "vendored"] }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
