[package]
name = "mangaread_org"
version = "0.5.2"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
scraper = "0.25"
wit-bindgen = { workspace = true }

[build-dependencies]
cargo-component = "0.21"
